//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingSystemDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceInstallment
    {
        public int InvoiceInstallmentId { get; set; }
        public int InvoiceId { get; set; }
        public int InstallmentId { get; set; }
    }
}
