//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingSystemDataModel
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int PaymentId { get; set; }
        public string PaymentMethod { get; set; }
        public string PaymentFrom { get; set; }
        public double Amount { get; set; }
        public string BillAccountNumber { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public string InvoiceNumber { get; set; }
        public string PaymentStatus { get; set; }
        public string PaymentReference { get; set; }
        public int BillAccountId { get; set; }
        
        [JsonIgnore]
        public virtual BillAccount BillAccount { get; set; }
    }
}
